version: '2'
services:

  nlpEngine:
    build: ./nlpEngine
    environment:
      - PORT=8000
    expose:
      - 8000
    command: python3 app.py
  
  webApp:
    build: ./webApp
    restart: always
    environment:
      - NODE_ENV=production
      - MONGODB=mongodb://mongodb/server-starter
      - PORT=3100
      - DIGEST_NAME=sha256
      - SECRET_KEY=SERVER_STARTER
      - NLP_ENGINE=http://nlpEngine:8000
      - DEFAULT_PASSWORD=123456
    ports:
      - 3100:3100
    links:
      - mongodb
      - nlpEngine
    command: node index.js

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    expose:
      - 27017